# Configuration for leths server
# The server connects to omegas an initializes them with different
# features. The connection is via ipv6 local link addresses.
default:
  interface: en7 # the interface for ipv6 local
  port: 11200 # the default port the lethd api listens on

omegas:
  text:
#    settings: [{color: 'ffffff', text: 'Des Menschen Seele  Gleicht dem Wasser:  Vom Himmel kommt es,  Zum Himmel steigt es,  Und wieder nieder  Zur Erde muss es.  Ewig wechselnd.  -  Strömt von der hohen,  Steilen Felsenwand  Der reine Strahl,  Dann stäubt er lieblich  In Wolkenwellen  Zum glatten Fels,  Und, leicht empfangen,  Wallt er verschleiernd,  Leisrauschend  Zur Tiefe nieder.  -  Ragen Klippen  Dem Sturz entgegen,  Schäumt er unmutig  Stufenweise  Zum Abgrund.  -  Im flachen Bette  Schleicht er das Wiesental hin,  Und in dem glatten See  Weiden ihr Antlitz  Alle Gestirne. - Wind ist der Welle  Lieblicher Buhler;  Wind rauscht von Grund aus  Schäumende Wogen.  -  Seele des Menschen  Wie gleichst du dem Wasser!  Schicksal des Menschen,  Wie gleichst du dem Wind!' }]
#    settings: [{color: 'ffffff', text: 'The quick brown fox jumps over the lazy dog +++ 0123456789+"*$%&/()=,;.:-_!?^~` +++ THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG +++ ' }]
#    settings: [{color: 'ffffff', text: 'Benno Eddi Rolf - Wolf +++ Sue Claire Trine - Biene +++ '}]
#    settings: [{ scene: 'scenes/rainbow.json' }]
    settings: [{ scene: 'scenes/pactext.json' }]
    scrollSettings: { stepx: 1, stepy: 0, steps: -1, interval: 25, roundoffsets: true }
    texts:

      # luz test unit
#      - { addr: 'fe80::42a3:6bff:fec1:8397', gridcoordinate: "B1", text: [ { cols: 72, offset: 766, orientation: 0 } ] }
#      - { addr: 'fe80::4d2:eda4:a942:d178 11200', gridcoordinate: "B1", text: [ { cols: 72, offset: 766, orientation: 0 } ] }
      - { addr: '::1 11200', gridcoordinate: "B1", text: [ { cols: 72, offset: 0, orientation: 0 } ] }


  light:
    size: {x: 5, y: 7} # (N, M)
    lights: # starting at x=0, y=0 -> x=N, y=0 -> x=1, y=1 ...
      # row 0 -> y=0
      - { addr: '::1 11201', gridcoordinate: "B2" }

  neuron:
    movingAverageCount: 20 # Number of frames for moving average
    threshold: 250 # ad threshold to fire neuron
    numBodyLeds: 70
    neurons:
      # tested Neurons

      # D6
      - { addr: '::1 11202', gridcoordinate: "D6", x: 2, y : 4, numAxonLeds: 70}

